### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by govvin** [pistangmapa/2020#1]
![image](https://user-images.githubusercontent.com/5821688/74197420-6fa54c80-4c9a-11ea-9f66-31418954a3ab.png)

- [x] Twitter : https://twitter.com/pistangmapa
- [x] Mastodon: https://en.osm.town/@pistangmapa
- [x] Telegram: https://telegram.me/pistangmapa

For now, let's remove other links we don't have accounts for.

**Comment by benhur07b** [comment]
Updated in e4b4eac02a987edd68ac5699d6d24e45eea4c23e. Removed other socmed links.
