### ISSUE TITLE
Location map

### ISSUE THREAD

**Issue by govvin** [pistangmapa/2020#2]
Do you think it would be better if we have the zoom level  default to around 12? 

How about we try map tiles that look less busy than Mapnik? I'm thinking the likes of Mapy Base, OSM Stamen Watercolor, CyclOSM etc.

**Comment by seav** [comment]
> How about we try map tiles that look less busy than Mapnik? I'm thinking the likes of Mapy Base, OSM Stamen Watercolor, CyclOSM etc.

I agree with using a less-busy base map. For my other projects, I've been using the CARTO Voyager basemap: https://carto.com/help/building-maps/basemap-list/

For example, here is the Voyager in action: https://wmph.github.io/eph-historical-markers-map/

**Comment by benhur07b** [comment]
Updated in e4b4eac02a987edd68ac5699d6d24e45eea4c23e. Default zoom level 12, CARTO Voyager basemap. TY @seav for pointing me to Voyager. :)

**Comment by maning** [comment]
If possible use our style color scheme to the map.  Here's rough coloring using mapbox cartogram: https://apps.mapbox.com/cartogram/#13.69/10.30973/123.90349
 
<img width="1617" alt="Screenshot 2020-03-04 21 19 38" src="https://user-images.githubusercontent.com/353700/75883490-0ad6af80-5e5e-11ea-9816-d2db7c63a910.png">

**Comment by maning** [comment]
we are going virtual/global. this is not needed anymore.
