### ISSUE TITLE
Comms

### ISSUE THREAD

**Issue by govvin** [pistangmapa/2020#4]
- [ ] publish final sponsorship tiers
- [ ] update names, contact info of 2020 prospective sponsors
- [ ] draft letter for prospective sponsors
- [ ] send out letters by W9

**Comment by seav** [comment]
I think we should just leave this repo as specific to the website and its codebase. Other conference-related action items should probably be in a different repo, such as "2020-coordination" or something.

**Comment by govvin** [comment]
> I think we should just leave this repo as specific to the website and its codebase. Other conference-related action items should probably be in a different repo, such as "2020-coordination" or something.

I agree! I'll move these unrelated issues to the coord repo https://github.com/pistangmapa/pnm20-coord
