### ISSUE TITLE
PR campaign and promotion

### ISSUE THREAD

**Issue by govvin** [pistangmapa/2020#5]
- [ ] Meet with Marketing, PR, SocMed team
- [ ] Prepare timeline and activities, strategy
- [ ] Determine point
- [ ] weekly updates, at least starting March.
- [ ] delegate posting rights to SocMed user accounts

**Comment by seav** [comment]
I think we should just leave this repo as specific to the website and its codebase. Other conference-related action items should probably be in a different repo, such as "2020-coordination" or something.

**Comment by govvin** [comment]
I agree! Moving this to [PnM20 coord repo](https://github.com/pistangmapa/pnm20-coord).
